### ISSUE TITLE
CẦN FIX BUG KHẨN CẤP (ANVILGUI ERROR)

### ISSUE THREAD

**Issue by MeoNguOfficial** [minevn/dotman#55]
Version: Latest free version
Server version: 1.21.1 - LEAF

Log error:
```
[21:33:17 ERROR]: Could not pass event InventoryClickEvent to MineVNLib v1.1.5
java.lang.ExceptionInInitializerError: null
        at MineVNLib.jar/net.minevn.libs.anvilgui.AnvilGUI$Builder.<init>(AnvilGUI.java:400) ~[MineVNLib.jar:?]
        at DotMan.jar/net.minevn.dotman.providers.CardProvider.askCardInfo$openAnvil(CardProvider.kt:169) ~[DotMan.jar:?]
        at DotMan.jar/net.minevn.dotman.providers.CardProvider.askCardInfo$openAnvil$default(CardProvider.kt:168) ~[DotMan.jar:?]
        at DotMan.jar/net.minevn.dotman.providers.CardProvider.askCardInfo(CardProvider.kt:197) ~[DotMan.jar:?]
        at DotMan.jar/net.minevn.dotman.gui.CardPriceUI.build$lambda$3(CardPriceUI.kt:58) ~[DotMan.jar:?]
        at MineVNLib.jar/net.minevn.guiapi.GuiItemStack.onClick(GuiItemStack.java:120) ~[MineVNLib.jar:?]
        at MineVNLib.jar/net.minevn.guiapi.GuiInventory.onClick(GuiInventory.java:71) ~[MineVNLib.jar:?]
        at MineVNLib.jar/net.minevn.guiapi.GuiListener.onClick(GuiListener.java:27) ~[MineVNLib.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor437.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:65) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3371) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:190) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1492) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1502) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1346) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.1.jar:1.21.1-DEV-64e3cd9]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: AnvilGUI does not support bukkit server version "1.21.1-R0.1-SNAPSHOT"
        at MineVNLib.jar/net.minevn.libs.anvilgui.version.VersionMatcher.match(VersionMatcher.java:35) ~[MineVNLib.jar:?]
        at MineVNLib.jar/net.minevn.libs.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:42) ~[MineVNLib.jar:?]
        ... 32 more
```

**Comment by amadeusmz** [comment]
Bạn thử minevnlib bản mới nhất xem

https://github.com/minevn/minevn-library/releases
